name: frontend
description: "A new Flutter project for CafeApp."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  mobile_scanner: ^7.2.0
  geolocator: ^14.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_dotenv: ^6.0.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  local_auth: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  monochrome_icon: "assets/images/logo.png" #for android dark mode only
  